# Generated by Django 4.2.7 on 2024-03-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('region', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='user_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FaceMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.TextField()),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userdata')),
            ],
        ),
    ]
